name: dev-osgeo-r
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: geocompr/geocompr:dev-osgeo
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Build book
          run: |
            Rscript -e 'remotes::install_dev("tmap")'
            Rscript -e 'remotes::install_github("rspatial/raster")'
            Rscript -e 'remotes::install_github("r-spatial/sf")'
            Rscript -e 'bookdown::render_book("index.Rmd")'
          
