name: qgis-ext
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: geocompr/geocompr:qgis-ext
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build book
         run: Rscript -e 'bookdown::render_book("index.Rmd")'
# 
# 
# jobs:
#   node-docker:
#     runs-on: ubuntu-latest
#     container:
#       image: geocompr/geocompr:qgis-ext
#     steps:
#          - name: Build book
#            run: Rscript -e 'bookdown::render_book("index.Rmd")'
    
        
