name: qgis-ext
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: geocompr/geocompr:qgis-ext
    steps:
         - name: Build book
           run: Rscript -e 'bookdown::render_book("index.Rmd")'
    
        
